export default {
  "defaultProps": { "colorScheme": "action", "size": "md" },
  "baseStyle": {
    "transitionProperty": "common",
    "transitionDuration": "fast",
    "transitionTimingFunction": "ease-out",
    "cursor": "pointer",
    "textDecoration": "none",
    "outline": "none",
    "color": "inherit",
    fontWeight: 600,
    borderRadius: "sm",
    _hover: { "textDecoration": "underline" },
    _focusVisible: {
      outline: "0.125rem solid",
      outlineColor: "gray.300",
      outlineOffset: "0.125rem",
    },
  },
  "variants": {
    "inText": {
      color: "brand.500",
      _hover: { textDecoration: "underline" },
      _focus: { textDecoration: "underline" },
      _focusVisible: {
        outline: "0.125rem solid",
        outlineColor: "currentcolor",
        outlineOffset: "0.125rem",
      },
    },
    "navigationLink": {
      p: 3,
      borderRadius: "md",
      textDecoration: "none",
      _hover: { bg: "gray.50", textDecoration: "none" },
      _focusVisible: {
        bg: "gray.50",
        textDecoration: "none",
        outline: "0.125rem solid",
        outlineColor: "gray.300",
        outlineOffset: "0.125rem",
      },
      _active: { bg: "gray.100", textDecoration: "none" },
    },
    card: {
      fontWeight: 600,
      fontSize: "lg",
      color: "brand.500",
      lineHeight: "shorter",
      display: "flex",
      alignItems: "center",
      "svg": {
        marginLeft: "0.5rem",
        transition: "transform 0.25s ease",
      },
      backgroundImage:
        "linear-gradient(transparent calc(100% - 0.125rem), currentcolor 0.125rem)",
      backgroundRepeat: "no-repeat",
      backgroundSize: "0% 100%",
      transition: "background-size 0.25s ease",
      _hover: {
        backgroundSize: "calc(100% - 1.625rem) 100%",
        textDecoration: "none",
        "svg": { transform: "translateX(0.25rem)" },
      },
      _focusVisible: {
        backgroundSize: "calc(100% - 1.625rem) 100%",
        textDecoration: "none",
        "svg": { transform: "translateX(0.25rem)" },
      },
    },
    section: {
      fontWeight: 600,
      fontSize: "sm",
      color: "gray.500",
      lineHeight: "shorter",
      display: "flex",
      alignItems: "center",
      "svg": {
        marginLeft: "0.5rem",
        transition: "transform 0.25s ease",
      },
      backgroundImage:
        "linear-gradient(transparent calc(100% - 0.125rem), currentcolor 0.125rem)",
      backgroundRepeat: "no-repeat",
      backgroundSize: "0% 100%",
      transition: "background-size 0.25s ease",
      _hover: {
        backgroundSize: "calc(100% - 1.625rem) 100%",
        textDecoration: "none",
        "svg": { transform: "translateX(0.25rem)" },
      },
      _focusVisible: {
        backgroundSize: "calc(100% - 1.625rem) 100%",
        textDecoration: "none",
        "svg": { transform: "translateX(0.25rem)" },
      },
    },
  },
  "sizes": {},
}
