# Deploy the site to github pages on push to the main branch

name: Deploy GH Pages

on:
  push:
    branches:
      - "main"

env:
  NODE: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Cache out
        uses: actions/cache@v4
        id: cache-out
        with:
          path: out
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Install
        run: yarn install

      - name: Build
        run: yarn export
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          SHARE_URL: ${{ secrets.SHARE_URL }}
          BASE_PATH: ${{ secrets.BASE_PATH }}
          MAILCHIMP_ADDRESS: ${{ secrets.MAILCHIMP_ADDRESS }}
          NEXT_PUBLIC_MAILCHIMP_ADDRESS: ${{ secrets.NODE_PUBLIC_MAILCHIMP_ADDRESS }}
          NEXT_PUBLIC_MAILCHIMP_TIMEOUT: ${{ secrets.NODE_PUBLIC_MAILCHIMP_TIMEOUT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore out cache
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: out
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
